sudo: false
language: ruby
rvm:
  - 2.6.6
  - 2.7.2
  - 3.0.0
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libsodium-dev
  - gem update --system
  - gem --version
  - gem install bundler
